[#ftl]
[@b.head/]
[@b.toolbar title="修改出版社"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(exchangeSchool) theme="list"]
    [@b.textfield name="exchangeSchool.code" label="代码" value="${exchangeSchool.code!}" required="true" maxlength="20"/]
    [@b.textfield name="exchangeSchool.name" label="名称" value="${exchangeSchool.name!}" required="true" maxlength="20"/]
    [@b.startend label="有效期"
      name="exchangeSchool.beginOn,exchangeSchool.endOn" required="true,false"
      start=exchangeSchool.beginOn end=exchangeSchool.endOn format="date"/]
    [@b.textfield name="exchangeSchool.remark" label="备注" value="${exchangeSchool.remark!}" maxlength="3"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
